/********************************************************************
* cpPrecisionDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cpPrecisionDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecpPrecisionDict();
extern void G__cpp_setup_inheritancecpPrecisionDict();
extern void G__cpp_setup_typetablecpPrecisionDict();
extern void G__cpp_setup_memvarcpPrecisionDict();
extern void G__cpp_setup_globalcpPrecisionDict();
extern void G__cpp_setup_memfunccpPrecisionDict();
extern void G__cpp_setup_funccpPrecisionDict();
extern void G__set_cpp_environmentcpPrecisionDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__cpPrecisionDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__cpPrecisionDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__cpPrecisionDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__cpPrecisionDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
