/********************************************************************
* cpViolationPOT_separateDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error cpViolationPOT_separateDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablecpViolationPOT_separateDict();
extern void G__cpp_setup_inheritancecpViolationPOT_separateDict();
extern void G__cpp_setup_typetablecpViolationPOT_separateDict();
extern void G__cpp_setup_memvarcpViolationPOT_separateDict();
extern void G__cpp_setup_globalcpViolationPOT_separateDict();
extern void G__cpp_setup_memfunccpViolationPOT_separateDict();
extern void G__cpp_setup_funccpViolationPOT_separateDict();
extern void G__set_cpp_environmentcpViolationPOT_separateDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__cpViolationPOT_separateDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__cpViolationPOT_separateDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__cpViolationPOT_separateDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__cpViolationPOT_separateDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
