/********************************************************************
* sin23Precision_sec_octDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sin23Precision_sec_octDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablesin23Precision_sec_octDict();
extern void G__cpp_setup_inheritancesin23Precision_sec_octDict();
extern void G__cpp_setup_typetablesin23Precision_sec_octDict();
extern void G__cpp_setup_memvarsin23Precision_sec_octDict();
extern void G__cpp_setup_globalsin23Precision_sec_octDict();
extern void G__cpp_setup_memfuncsin23Precision_sec_octDict();
extern void G__cpp_setup_funcsin23Precision_sec_octDict();
extern void G__set_cpp_environmentsin23Precision_sec_octDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__sin23Precision_sec_octDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__sin23Precision_sec_octDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__sin23Precision_sec_octDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__sin23Precision_sec_octDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
